// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(InsmaScheduleContext))]
    [Migration("20260428094348_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dal.Entities.DbAcademicDiscipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcademicDisciplineTargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("academic_discipline_target_type");

                    b.PrimitiveCollection<string[]>("AssociatedNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("associated_names");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comment");

                    b.Property<bool>("HasExam")
                        .HasColumnType("boolean")
                        .HasColumnName("has_exam");

                    b.Property<bool>("HasTest")
                        .HasColumnType("boolean")
                        .HasColumnName("has_test");

                    b.Property<bool>("IsLabLessonsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lab_lessons_allowed");

                    b.Property<bool>("IsLectureLessonsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lecture_lessons_allowed");

                    b.Property<bool>("IsPracticeLessonsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_practice_lessons_allowed");

                    b.Property<int?>("LabTotalHoursCount")
                        .HasColumnType("integer")
                        .HasColumnName("lab_total_hours_count");

                    b.Property<int?>("LectureTotalHoursCount")
                        .HasColumnType("integer")
                        .HasColumnName("lecture_total_hours_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("PracticeTotalHoursCount")
                        .HasColumnType("integer")
                        .HasColumnName("practice_total_hours_count");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("SemesterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("semester_number");

                    b.HasKey("Id")
                        .HasName("pk_academic_discipline");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_academic_discipline_schedule_id");

                    b.ToTable("academic_discipline", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbCampus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_campus");

                    b.ToTable("campus", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcademicDisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_discipline_id");

                    b.Property<string>("AcademicDisciplineType")
                        .HasColumnType("text")
                        .HasColumnName("academic_discipline_type");

                    b.Property<bool>("AllowCombining")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_combining");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("Date")
                        .HasColumnName("date");

                    b.Property<string>("FlexibilityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flexibility_type");

                    b.Property<int?>("HoursCost")
                        .HasColumnType("integer")
                        .HasColumnName("hours_cost");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<TimeOnly?>("TimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_from");

                    b.Property<TimeOnly?>("TimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_to");

                    b.HasKey("Id")
                        .HasName("pk_lesson");

                    b.HasIndex("AcademicDisciplineId")
                        .HasDatabaseName("ix_lesson_academic_discipline_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_lesson_schedule_id");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowCombining")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_combining");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("Date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("Date")
                        .HasColumnName("date_to");

                    b.Property<string>("DayOfWeekTimeIntervals")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week_time_intervals");

                    b.Property<Guid?>("DbAcademicDisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_discipline_id");

                    b.Property<Guid?>("DbAcademicDisciplineId1")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_discipline_id1");

                    b.Property<Guid?>("DbAcademicDisciplineId2")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_discipline_id2");

                    b.Property<int?>("HoursCost")
                        .HasColumnType("integer")
                        .HasColumnName("hours_cost");

                    b.Property<string>("RepeatType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repeat_type");

                    b.HasKey("Id")
                        .HasName("pk_lesson_batch_info");

                    b.HasIndex("DbAcademicDisciplineId")
                        .HasDatabaseName("ix_lesson_batch_info_db_academic_discipline_id");

                    b.HasIndex("DbAcademicDisciplineId1")
                        .HasDatabaseName("ix_lesson_batch_info_db_academic_discipline_id1");

                    b.HasIndex("DbAcademicDisciplineId2")
                        .HasDatabaseName("ix_lesson_batch_info_db_academic_discipline_id2");

                    b.ToTable("lesson_batch_info", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonValidationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AffectedByAcademicDisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_academic_discipline_id");

                    b.Property<string>("AffectedByAcademicDisciplineType")
                        .HasColumnType("text")
                        .HasColumnName("affected_by_academic_discipline_type");

                    b.Property<Guid?>("AffectedByLessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_lesson_id");

                    b.Property<Guid?>("AffectedByStudentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_student_group_id");

                    b.Property<Guid?>("AffectedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_teacher_id");

                    b.Property<Guid?>("AffectedByTeacherPreferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_teacher_preference_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_type");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message");

                    b.HasKey("Id")
                        .HasName("pk_lesson_validation_message");

                    b.HasIndex("AffectedByAcademicDisciplineId")
                        .HasDatabaseName("ix_lesson_validation_message_affected_by_academic_discipline_id");

                    b.HasIndex("AffectedByLessonId")
                        .HasDatabaseName("ix_lesson_validation_message_affected_by_lesson_id");

                    b.HasIndex("AffectedByStudentGroupId")
                        .HasDatabaseName("ix_lesson_validation_message_affected_by_student_group_id");

                    b.HasIndex("AffectedByTeacherId")
                        .HasDatabaseName("ix_lesson_validation_message_affected_by_teacher_id");

                    b.HasIndex("AffectedByTeacherPreferenceId")
                        .HasDatabaseName("ix_lesson_validation_message_affected_by_teacher_preference_id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_lesson_validation_message_lesson_id");

                    b.ToTable("lesson_validation_message", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<bool?>("HasProjector")
                        .HasColumnType("boolean")
                        .HasColumnName("has_projector");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RoomBoardType")
                        .HasColumnType("text")
                        .HasColumnName("room_board_type");

                    b.Property<string>("RoomType")
                        .HasColumnType("text")
                        .HasColumnName("room_type");

                    b.HasKey("Id")
                        .HasName("pk_room");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_room_campus_id");

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("Date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("Date")
                        .HasColumnName("date_to");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_schedule");

                    b.ToTable("schedule", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.HasIndex("StudentGroupId")
                        .HasDatabaseName("ix_student_student_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_student_user_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbStudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("SemesterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("semester_number");

                    b.Property<string>("StudentGroupType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_group_type");

                    b.HasKey("Id")
                        .HasName("pk_student_group");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_student_group_schedule_id");

                    b.ToTable("student_group", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contacts")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("contacts");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.HasKey("Id")
                        .HasName("pk_teacher");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbTeacherPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comment");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<string>("TeacherPreferenceType")
                        .HasColumnType("text")
                        .HasColumnName("teacher_preference_type");

                    b.Property<TimeOnly?>("TimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_from");

                    b.Property<TimeOnly?>("TimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_to");

                    b.HasKey("Id")
                        .HasName("pk_teacher_preference");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_teacher_preference_room_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_teacher_preference_schedule_id");

                    b.HasIndex("TeacherId")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_preference_teacher_id");

                    b.ToTable("teacher_preference", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("lesson_batch_info_room", b =>
                {
                    b.Property<Guid>("room_id")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("lesson_batch_info_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.HasKey("room_id", "lesson_batch_info_id")
                        .HasName("pk_lesson_batch_info_room_dictionary_string_object");

                    b.HasIndex("lesson_batch_info_id")
                        .HasDatabaseName("ix_lesson_batch_info_room_dictionary_string_object_lesson");

                    b.ToTable("lesson_batch_info_room (_dictionary<string, object>)", (string)null);
                });

            modelBuilder.Entity("lesson_batch_info_student_group", b =>
                {
                    b.Property<Guid>("student_group_id")
                        .HasColumnType("uuid")
                        .HasColumnName("student_group_id");

                    b.Property<Guid>("lesson_batch_info_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.HasKey("student_group_id", "lesson_batch_info_id")
                        .HasName("pk_lesson_batch_info_student_group_dictionary_string_object");

                    b.HasIndex("lesson_batch_info_id")
                        .HasDatabaseName("ix_lesson_batch_info_student_group_dictionary_string_object");

                    b.ToTable("lesson_batch_info_student_group (_dictionary<string, object>)", (string)null);
                });

            modelBuilder.Entity("lesson_batch_info_teacher", b =>
                {
                    b.Property<Guid>("teacher_id")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<Guid>("lesson_batch_info_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.HasKey("teacher_id", "lesson_batch_info_id")
                        .HasName("pk_lesson_batch_info_teacher_dictionary_string_object");

                    b.HasIndex("lesson_batch_info_id")
                        .HasDatabaseName("ix_lesson_batch_info_teacher_dictionary_string_object_les");

                    b.ToTable("lesson_batch_info_teacher (_dictionary<string, object>)", (string)null);
                });

            modelBuilder.Entity("lesson_room", b =>
                {
                    b.Property<Guid>("room_id")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("lesson_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.HasKey("room_id", "lesson_id")
                        .HasName("pk_lesson_room_dictionary_string_object");

                    b.HasIndex("lesson_id")
                        .HasDatabaseName("ix_lesson_room_dictionary_string_object_lesson_id");

                    b.ToTable("lesson_room (_dictionary<string, object>)", (string)null);
                });

            modelBuilder.Entity("lesson_student_group", b =>
                {
                    b.Property<Guid>("student_group_id")
                        .HasColumnType("uuid")
                        .HasColumnName("student_group_id");

                    b.Property<Guid>("lesson_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.HasKey("student_group_id", "lesson_id")
                        .HasName("pk_lesson_student_group_dictionary_string_object");

                    b.HasIndex("lesson_id")
                        .HasDatabaseName("ix_lesson_student_group_dictionary_string_object_lesson_id");

                    b.ToTable("lesson_student_group (_dictionary<string, object>)", (string)null);
                });

            modelBuilder.Entity("lesson_teacher", b =>
                {
                    b.Property<Guid>("teacher_id")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<Guid>("lesson_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.HasKey("teacher_id", "lesson_id")
                        .HasName("pk_lesson_teacher_dictionary_string_object");

                    b.HasIndex("lesson_id")
                        .HasDatabaseName("ix_lesson_teacher_dictionary_string_object_lesson_id");

                    b.ToTable("lesson_teacher (_dictionary<string, object>)", (string)null);
                });

            modelBuilder.Entity("student_group_hierarchy", b =>
                {
                    b.Property<Guid>("parent_id")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("child_id")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.HasKey("parent_id", "child_id")
                        .HasName("pk_student_group_hierarchy_dictionary_string_object");

                    b.HasIndex("child_id")
                        .HasDatabaseName("ix_student_group_hierarchy_dictionary_string_object_child");

                    b.ToTable("student_group_hierarchy (_dictionary<string, object>)", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbAcademicDiscipline", b =>
                {
                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academic_discipline_db_schedule_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Dal.Entities.DbLesson", b =>
                {
                    b.HasOne("Dal.Entities.DbAcademicDiscipline", "AcademicDiscipline")
                        .WithMany()
                        .HasForeignKey("AcademicDisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lesson_academic_discipline_academic_discipline_id");

                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_db_schedule_schedule_id");

                    b.Navigation("AcademicDiscipline");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfo", b =>
                {
                    b.HasOne("Dal.Entities.DbAcademicDiscipline", null)
                        .WithMany("AcademicDisciplineLabLessonBatchInfos")
                        .HasForeignKey("DbAcademicDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_batch_info_lab");

                    b.HasOne("Dal.Entities.DbAcademicDiscipline", null)
                        .WithMany("AcademicDisciplineLectureLessonBatchInfos")
                        .HasForeignKey("DbAcademicDisciplineId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_batch_info_lecture");

                    b.HasOne("Dal.Entities.DbAcademicDiscipline", null)
                        .WithMany("AcademicDisciplinePracticeLessonBatchInfos")
                        .HasForeignKey("DbAcademicDisciplineId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_batch_info_practice");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonValidationMessage", b =>
                {
                    b.HasOne("Dal.Entities.DbAcademicDiscipline", "AffectedByAcademicDiscipline")
                        .WithMany()
                        .HasForeignKey("AffectedByAcademicDisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lesson_validation_message_academic_discipline_affected_by_a");

                    b.HasOne("Dal.Entities.DbLesson", "AffectedByLesson")
                        .WithMany()
                        .HasForeignKey("AffectedByLessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lesson_validation_message_lesson_affected_by_lesson_id");

                    b.HasOne("Dal.Entities.DbStudentGroup", "AffectedByStudentGroup")
                        .WithMany()
                        .HasForeignKey("AffectedByStudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lesson_validation_message_db_student_group_affected_by_stud");

                    b.HasOne("Dal.Entities.DbTeacher", "AffectedByTeacher")
                        .WithMany()
                        .HasForeignKey("AffectedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lesson_validation_message_db_teacher_affected_by_teacher_id");

                    b.HasOne("Dal.Entities.DbTeacherPreference", "AffectedByTeacherPreference")
                        .WithMany()
                        .HasForeignKey("AffectedByTeacherPreferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lesson_validation_message_db_teacher_preference_affected_by");

                    b.HasOne("Dal.Entities.DbLesson", "Lesson")
                        .WithMany("ValidationMessages")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_validation_message_lesson_lesson_id");

                    b.Navigation("AffectedByAcademicDiscipline");

                    b.Navigation("AffectedByLesson");

                    b.Navigation("AffectedByStudentGroup");

                    b.Navigation("AffectedByTeacher");

                    b.Navigation("AffectedByTeacherPreference");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Dal.Entities.DbRoom", b =>
                {
                    b.HasOne("Dal.Entities.DbCampus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_campus_campus_id");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Dal.Entities.DbStudent", b =>
                {
                    b.HasOne("Dal.Entities.DbStudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_db_student_group_student_group_id");

                    b.HasOne("Dal.Entities.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_db_user_user_id");

                    b.Navigation("StudentGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dal.Entities.DbStudentGroup", b =>
                {
                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_group_schedule_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Dal.Entities.DbTeacherPreference", b =>
                {
                    b.HasOne("Dal.Entities.DbRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_teacher_preference_room_room_id");

                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_preference_schedule_schedule_id");

                    b.HasOne("Dal.Entities.DbTeacher", "Teacher")
                        .WithOne()
                        .HasForeignKey("Dal.Entities.DbTeacherPreference", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_preference_teacher_teacher_id");

                    b.Navigation("Room");

                    b.Navigation("Schedule");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("lesson_batch_info_room", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", null)
                        .WithMany()
                        .HasForeignKey("lesson_batch_info_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_room_lesson_batch_info");

                    b.HasOne("Dal.Entities.DbRoom", null)
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_room_room");
                });

            modelBuilder.Entity("lesson_batch_info_student_group", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", null)
                        .WithMany()
                        .HasForeignKey("lesson_batch_info_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_student_group_lesson_batch_info");

                    b.HasOne("Dal.Entities.DbStudentGroup", null)
                        .WithMany()
                        .HasForeignKey("student_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_student_group_student_group");
                });

            modelBuilder.Entity("lesson_batch_info_teacher", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", null)
                        .WithMany()
                        .HasForeignKey("lesson_batch_info_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_teacher_lesson_batch_info");

                    b.HasOne("Dal.Entities.DbTeacher", null)
                        .WithMany()
                        .HasForeignKey("teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_teacher_teacher");
                });

            modelBuilder.Entity("lesson_room", b =>
                {
                    b.HasOne("Dal.Entities.DbLesson", null)
                        .WithMany()
                        .HasForeignKey("lesson_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_room_lesson");

                    b.HasOne("Dal.Entities.DbRoom", null)
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_room_room");
                });

            modelBuilder.Entity("lesson_student_group", b =>
                {
                    b.HasOne("Dal.Entities.DbLesson", null)
                        .WithMany()
                        .HasForeignKey("lesson_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_student_group_lesson");

                    b.HasOne("Dal.Entities.DbStudentGroup", null)
                        .WithMany()
                        .HasForeignKey("student_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_student_group_student_group");
                });

            modelBuilder.Entity("lesson_teacher", b =>
                {
                    b.HasOne("Dal.Entities.DbLesson", null)
                        .WithMany()
                        .HasForeignKey("lesson_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_teacher_lesson");

                    b.HasOne("Dal.Entities.DbTeacher", null)
                        .WithMany()
                        .HasForeignKey("teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_teacher_teacher");
                });

            modelBuilder.Entity("student_group_hierarchy", b =>
                {
                    b.HasOne("Dal.Entities.DbStudentGroup", null)
                        .WithMany()
                        .HasForeignKey("child_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_group_hierarchy_child");

                    b.HasOne("Dal.Entities.DbStudentGroup", null)
                        .WithMany()
                        .HasForeignKey("parent_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_group_hierarchy_parent");
                });

            modelBuilder.Entity("Dal.Entities.DbAcademicDiscipline", b =>
                {
                    b.Navigation("AcademicDisciplineLabLessonBatchInfos");

                    b.Navigation("AcademicDisciplineLectureLessonBatchInfos");

                    b.Navigation("AcademicDisciplinePracticeLessonBatchInfos");
                });

            modelBuilder.Entity("Dal.Entities.DbLesson", b =>
                {
                    b.Navigation("ValidationMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
