// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(InsmaScheduleContext))]
    [Migration("20260511180114_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dal.Entities.DbAcademicDiscipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcademicDisciplineTargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("academic_discipline_target_type");

                    b.PrimitiveCollection<string[]>("AssociatedNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("associated_names");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comment");

                    b.Property<bool>("IsExamLessonsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exam_lessons_allowed");

                    b.Property<bool>("IsLabLessonsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lab_lessons_allowed");

                    b.Property<bool>("IsLectureLessonsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_lecture_lessons_allowed");

                    b.Property<bool>("IsPracticeLessonsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_practice_lessons_allowed");

                    b.Property<bool>("IsTestLessonsAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_test_lessons_allowed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("SemesterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("semester_number");

                    b.HasKey("Id")
                        .HasName("pk_academic_discipline");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_academic_discipline_schedule_id");

                    b.ToTable("academic_discipline", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbCampus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_campus");

                    b.ToTable("campus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f68b22ca-dc97-4aed-ab4f-db709e670d36"),
                            Name = "Куйбышева"
                        },
                        new
                        {
                            Id = new Guid("453addd1-7fc7-4028-9e1c-bf042c2164a3"),
                            Name = "Тургенева"
                        });
                });

            modelBuilder.Entity("Dal.Entities.DbLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcademicDisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_discipline_id");

                    b.Property<string>("AcademicDisciplineType")
                        .HasColumnType("text")
                        .HasColumnName("academic_discipline_type");

                    b.Property<bool>("AllowCombining")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_combining");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("Date")
                        .HasColumnName("date");

                    b.Property<string>("FlexibilityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flexibility_type");

                    b.Property<int?>("HoursCost")
                        .HasColumnType("integer")
                        .HasColumnName("hours_cost");

                    b.Property<Guid?>("LessonBatchInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<TimeOnly?>("TimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_from");

                    b.Property<TimeOnly?>("TimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_to");

                    b.HasKey("Id")
                        .HasName("pk_lesson");

                    b.HasIndex("AcademicDisciplineId")
                        .HasDatabaseName("ix_lesson_academic_discipline_id");

                    b.HasIndex("LessonBatchInfoId")
                        .HasDatabaseName("ix_lesson_lesson_batch_info_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_lesson_schedule_id");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowCombining")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_combining");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("Date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("Date")
                        .HasColumnName("date_to");

                    b.Property<string>("DayOfWeekTimeIntervals")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week_time_intervals");

                    b.Property<int?>("HoursCost")
                        .HasColumnType("integer")
                        .HasColumnName("hours_cost");

                    b.Property<string>("RepeatType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repeat_type");

                    b.Property<int?>("TotalHoursCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_hours_count");

                    b.Property<Guid?>("exam_academic_discipline_id")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_academic_discipline_id");

                    b.Property<Guid?>("lab_academic_discipline_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_academic_discipline_id");

                    b.Property<Guid?>("lecture_academic_discipline_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lecture_academic_discipline_id");

                    b.Property<Guid?>("practice_academic_discipline_id")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_academic_discipline_id");

                    b.Property<Guid?>("test_academic_discipline_id")
                        .HasColumnType("uuid")
                        .HasColumnName("test_academic_discipline_id");

                    b.HasKey("Id")
                        .HasName("pk_lesson_batch_info");

                    b.HasIndex("exam_academic_discipline_id")
                        .HasDatabaseName("ix_lesson_batch_info_exam_academic_discipline_id");

                    b.HasIndex("lab_academic_discipline_id")
                        .HasDatabaseName("ix_lesson_batch_info_lab_academic_discipline_id");

                    b.HasIndex("lecture_academic_discipline_id")
                        .HasDatabaseName("ix_lesson_batch_info_lecture_academic_discipline_id");

                    b.HasIndex("practice_academic_discipline_id")
                        .HasDatabaseName("ix_lesson_batch_info_practice_academic_discipline_id");

                    b.HasIndex("test_academic_discipline_id")
                        .HasDatabaseName("ix_lesson_batch_info_test_academic_discipline_id");

                    b.ToTable("lesson_batch_info", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfoRoom", b =>
                {
                    b.Property<Guid>("LessonBatchInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("LessonBatchInfoId", "RoomId")
                        .HasName("pk_lesson_batch_info_room");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_lesson_batch_info_room_room_id");

                    b.ToTable("lesson_batch_info_room", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfoStudentGroup", b =>
                {
                    b.Property<Guid>("LessonBatchInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_group_id");

                    b.HasKey("LessonBatchInfoId", "StudentGroupId")
                        .HasName("pk_lesson_batch_info_student_group");

                    b.HasIndex("StudentGroupId")
                        .HasDatabaseName("ix_lesson_batch_info_student_group_student_group_id");

                    b.ToTable("lesson_batch_info_student_group", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfoTeacher", b =>
                {
                    b.Property<Guid>("LessonBatchInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("LessonBatchInfoId", "TeacherId")
                        .HasName("pk_lesson_batch_info_teacher");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_lesson_batch_info_teacher_teacher_id");

                    b.ToTable("lesson_batch_info_teacher", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonPolicyViolation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AffectedByAcademicDisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_academic_discipline_id");

                    b.Property<string>("AffectedByAcademicDisciplineType")
                        .HasColumnType("text")
                        .HasColumnName("affected_by_academic_discipline_type");

                    b.Property<Guid?>("AffectedByLessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_lesson_id");

                    b.Property<Guid?>("AffectedByStudentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_student_group_id");

                    b.Property<Guid?>("AffectedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_teacher_id");

                    b.Property<Guid?>("AffectedByTeacherPreferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_by_teacher_preference_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_type");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.HasKey("Id")
                        .HasName("pk_lesson_policy_violation");

                    b.HasIndex("AffectedByAcademicDisciplineId")
                        .HasDatabaseName("ix_lesson_policy_violation_affected_by_academic_discipline_id");

                    b.HasIndex("AffectedByLessonId")
                        .HasDatabaseName("ix_lesson_policy_violation_affected_by_lesson_id");

                    b.HasIndex("AffectedByStudentGroupId")
                        .HasDatabaseName("ix_lesson_policy_violation_affected_by_student_group_id");

                    b.HasIndex("AffectedByTeacherId")
                        .HasDatabaseName("ix_lesson_policy_violation_affected_by_teacher_id");

                    b.HasIndex("AffectedByTeacherPreferenceId")
                        .HasDatabaseName("ix_lesson_policy_violation_affected_by_teacher_preference_id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_lesson_policy_violation_lesson_id");

                    b.ToTable("lesson_policy_violation", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonRoom", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("LessonId", "RoomId")
                        .HasName("pk_lesson_room");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_lesson_room_room_id");

                    b.ToTable("lesson_room", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonStudentGroup", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_group_id");

                    b.HasKey("LessonId", "StudentGroupId")
                        .HasName("pk_lesson_student_group");

                    b.HasIndex("StudentGroupId")
                        .HasDatabaseName("ix_lesson_student_group_student_group_id");

                    b.ToTable("lesson_student_group", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonTeacher", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("LessonId", "TeacherId")
                        .HasName("pk_lesson_teacher");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_lesson_teacher_teacher_id");

                    b.ToTable("lesson_teacher", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<bool?>("HasProjector")
                        .HasColumnType("boolean")
                        .HasColumnName("has_projector");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RoomBoardType")
                        .HasColumnType("text")
                        .HasColumnName("room_board_type");

                    b.Property<string>("RoomType")
                        .HasColumnType("text")
                        .HasColumnName("room_type");

                    b.HasKey("Id")
                        .HasName("pk_room");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_room_campus_id");

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("Date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("Date")
                        .HasColumnName("date_to");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_schedule");

                    b.ToTable("schedule", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.HasIndex("StudentGroupId")
                        .HasDatabaseName("ix_student_student_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_student_user_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbStudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("SemesterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("semester_number");

                    b.Property<string>("StudentGroupType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_group_type");

                    b.Property<int?>("StudentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("students_count");

                    b.HasKey("Id")
                        .HasName("pk_student_group");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_student_group_schedule_id");

                    b.ToTable("student_group", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbStudentGroupLink", b =>
                {
                    b.Property<Guid>("ChildStudentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_student_group_id");

                    b.Property<Guid>("ParentStudentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_student_group_id");

                    b.HasKey("ChildStudentGroupId", "ParentStudentGroupId")
                        .HasName("pk_student_group_link");

                    b.HasIndex("ParentStudentGroupId")
                        .HasDatabaseName("ix_student_group_link_parent_student_group_id");

                    b.ToTable("student_group_link", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contacts")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("contacts");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.HasKey("Id")
                        .HasName("pk_teacher");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbTeacherPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comment");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<string>("TeacherPreferenceType")
                        .HasColumnType("text")
                        .HasColumnName("teacher_preference_type");

                    b.Property<TimeOnly?>("TimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_from");

                    b.Property<TimeOnly?>("TimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_to");

                    b.HasKey("Id")
                        .HasName("pk_teacher_preference");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_teacher_preference_room_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_teacher_preference_schedule_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_teacher_preference_teacher_id");

                    b.ToTable("teacher_preference", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbAcademicDiscipline", b =>
                {
                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academic_discipline_db_schedule_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Dal.Entities.DbLesson", b =>
                {
                    b.HasOne("Dal.Entities.DbAcademicDiscipline", "AcademicDiscipline")
                        .WithMany()
                        .HasForeignKey("AcademicDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_academic_discipline_academic_discipline_id");

                    b.HasOne("Dal.Entities.DbLessonBatchInfo", "LessonBatchInfo")
                        .WithMany()
                        .HasForeignKey("LessonBatchInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_db_lesson_batch_info_lesson_batch_info_id");

                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_db_schedule_schedule_id");

                    b.Navigation("AcademicDiscipline");

                    b.Navigation("LessonBatchInfo");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfo", b =>
                {
                    b.HasOne("Dal.Entities.DbAcademicDiscipline", null)
                        .WithMany("AcademicDisciplineExamLessonBatchInfos")
                        .HasForeignKey("exam_academic_discipline_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_batch_info_exam");

                    b.HasOne("Dal.Entities.DbAcademicDiscipline", null)
                        .WithMany("AcademicDisciplineLabLessonBatchInfos")
                        .HasForeignKey("lab_academic_discipline_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_batch_info_lab");

                    b.HasOne("Dal.Entities.DbAcademicDiscipline", null)
                        .WithMany("AcademicDisciplineLectureLessonBatchInfos")
                        .HasForeignKey("lecture_academic_discipline_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_batch_info_lecture");

                    b.HasOne("Dal.Entities.DbAcademicDiscipline", null)
                        .WithMany("AcademicDisciplinePracticeLessonBatchInfos")
                        .HasForeignKey("practice_academic_discipline_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_batch_info_practice");

                    b.HasOne("Dal.Entities.DbAcademicDiscipline", null)
                        .WithMany("AcademicDisciplineTestLessonBatchInfos")
                        .HasForeignKey("test_academic_discipline_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_batch_info_test");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfoRoom", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", "LessonBatchInfo")
                        .WithMany("Rooms")
                        .HasForeignKey("LessonBatchInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_room_lesson_batch_info_lesson_batch_info_");

                    b.HasOne("Dal.Entities.DbRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_room_db_room_room_id");

                    b.Navigation("LessonBatchInfo");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfoStudentGroup", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", "LessonBatchInfo")
                        .WithMany("StudentGroups")
                        .HasForeignKey("LessonBatchInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_student_group_lesson_batch_info_lesson_ba");

                    b.HasOne("Dal.Entities.DbStudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_student_group_db_student_group_student_gr");

                    b.Navigation("LessonBatchInfo");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfoTeacher", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", "LessonBatchInfo")
                        .WithMany("Teachers")
                        .HasForeignKey("LessonBatchInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_teacher_lesson_batch_info_lesson_batch_in");

                    b.HasOne("Dal.Entities.DbTeacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_teacher_db_teacher_teacher_id");

                    b.Navigation("LessonBatchInfo");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonPolicyViolation", b =>
                {
                    b.HasOne("Dal.Entities.DbAcademicDiscipline", "AffectedByAcademicDiscipline")
                        .WithMany()
                        .HasForeignKey("AffectedByAcademicDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_policy_violation_academic_discipline_affected_by_aca");

                    b.HasOne("Dal.Entities.DbLesson", "AffectedByLesson")
                        .WithMany()
                        .HasForeignKey("AffectedByLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_policy_violation_lesson_affected_by_lesson_id");

                    b.HasOne("Dal.Entities.DbStudentGroup", "AffectedByStudentGroup")
                        .WithMany()
                        .HasForeignKey("AffectedByStudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_policy_violation_db_student_group_affected_by_studen");

                    b.HasOne("Dal.Entities.DbTeacher", "AffectedByTeacher")
                        .WithMany()
                        .HasForeignKey("AffectedByTeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_policy_violation_db_teacher_affected_by_teacher_id");

                    b.HasOne("Dal.Entities.DbTeacherPreference", "AffectedByTeacherPreference")
                        .WithMany()
                        .HasForeignKey("AffectedByTeacherPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_policy_violation_db_teacher_preference_affected_by_t");

                    b.HasOne("Dal.Entities.DbLesson", "Lesson")
                        .WithMany("Violations")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_policy_violation_lesson_lesson_id");

                    b.Navigation("AffectedByAcademicDiscipline");

                    b.Navigation("AffectedByLesson");

                    b.Navigation("AffectedByStudentGroup");

                    b.Navigation("AffectedByTeacher");

                    b.Navigation("AffectedByTeacherPreference");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonRoom", b =>
                {
                    b.HasOne("Dal.Entities.DbLesson", "Lesson")
                        .WithMany("Rooms")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_room_lesson_lesson_id");

                    b.HasOne("Dal.Entities.DbRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_room_db_room_room_id");

                    b.Navigation("Lesson");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonStudentGroup", b =>
                {
                    b.HasOne("Dal.Entities.DbLesson", "Lesson")
                        .WithMany("StudentGroups")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_student_group_lesson_lesson_id");

                    b.HasOne("Dal.Entities.DbStudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_student_group_db_student_group_student_group_id");

                    b.Navigation("Lesson");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonTeacher", b =>
                {
                    b.HasOne("Dal.Entities.DbLesson", "Lesson")
                        .WithMany("Teachers")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_teacher_lesson_lesson_id");

                    b.HasOne("Dal.Entities.DbTeacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_teacher_db_teacher_teacher_id");

                    b.Navigation("Lesson");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Dal.Entities.DbRoom", b =>
                {
                    b.HasOne("Dal.Entities.DbCampus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_campus_campus_id");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Dal.Entities.DbStudent", b =>
                {
                    b.HasOne("Dal.Entities.DbStudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_db_student_group_student_group_id");

                    b.HasOne("Dal.Entities.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_db_user_user_id");

                    b.Navigation("StudentGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dal.Entities.DbStudentGroup", b =>
                {
                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_group_schedule_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Dal.Entities.DbStudentGroupLink", b =>
                {
                    b.HasOne("Dal.Entities.DbStudentGroup", "ChildStudentGroup")
                        .WithMany("Parents")
                        .HasForeignKey("ChildStudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_group_link_student_group_child_student_group_id");

                    b.HasOne("Dal.Entities.DbStudentGroup", "ParentStudentGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentStudentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_group_link_student_group_parent_student_group_id");

                    b.Navigation("ChildStudentGroup");

                    b.Navigation("ParentStudentGroup");
                });

            modelBuilder.Entity("Dal.Entities.DbTeacherPreference", b =>
                {
                    b.HasOne("Dal.Entities.DbRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_teacher_preference_room_room_id");

                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_preference_schedule_schedule_id");

                    b.HasOne("Dal.Entities.DbTeacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_preference_teacher_teacher_id");

                    b.Navigation("Room");

                    b.Navigation("Schedule");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Dal.Entities.DbAcademicDiscipline", b =>
                {
                    b.Navigation("AcademicDisciplineExamLessonBatchInfos");

                    b.Navigation("AcademicDisciplineLabLessonBatchInfos");

                    b.Navigation("AcademicDisciplineLectureLessonBatchInfos");

                    b.Navigation("AcademicDisciplinePracticeLessonBatchInfos");

                    b.Navigation("AcademicDisciplineTestLessonBatchInfos");
                });

            modelBuilder.Entity("Dal.Entities.DbLesson", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("StudentGroups");

                    b.Navigation("Teachers");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfo", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("StudentGroups");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Dal.Entities.DbStudentGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
