// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dal.Migrations
{
    [DbContext(typeof(InsmaScheduleContext))]
    partial class InsmaScheduleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dal.Entities.DbAcademicDiscipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcademicDisciplineTargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("academic_discipline_target_type");

                    b.Property<string>("AllowedLessonTypes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("allowed_lesson_types");

                    b.PrimitiveCollection<string[]>("AssociatedNames")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("associated_names");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("SemesterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("semester_number");

                    b.HasKey("Id")
                        .HasName("pk_academic_discipline");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_academic_discipline_schedule_id");

                    b.ToTable("academic_discipline", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbCampus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_campus");

                    b.ToTable("campus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f68b22ca-dc97-4aed-ab4f-db709e670d36"),
                            Name = "Куйбышева"
                        },
                        new
                        {
                            Id = new Guid("453addd1-7fc7-4028-9e1c-bf042c2164a3"),
                            Name = "Тургенева"
                        });
                });

            modelBuilder.Entity("Dal.Entities.DbDayOfWeekTimeIntervalAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<Guid>("LessonBatchInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<TimeOnly>("TimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_from");

                    b.Property<TimeOnly>("TimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_to");

                    b.HasKey("Id")
                        .HasName("pk_day_of_week_time_interval_assignment");

                    b.HasIndex("LessonBatchInfoId")
                        .HasDatabaseName("ix_day_of_week_time_interval_assignment_lesson_batch_info_id");

                    b.ToTable("day_of_week_time_interval_assignment", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowCombining")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_combining");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("Date")
                        .HasColumnName("date");

                    b.Property<Guid?>("DayOfWeekTimeIntervalAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("day_of_week_time_interval_assignment_id");

                    b.Property<bool>("DetachedFromBatch")
                        .HasColumnType("boolean")
                        .HasColumnName("detached_from_batch");

                    b.Property<string>("FlexibilityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flexibility_type");

                    b.Property<int?>("HoursCost")
                        .HasColumnType("integer")
                        .HasColumnName("hours_cost");

                    b.Property<Guid>("LessonBatchInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<TimeOnly?>("TimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_from");

                    b.Property<TimeOnly?>("TimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_to");

                    b.HasKey("Id")
                        .HasName("pk_lesson");

                    b.HasIndex("DayOfWeekTimeIntervalAssignmentId")
                        .HasDatabaseName("ix_lesson_day_of_week_time_interval_assignment_id");

                    b.HasIndex("LessonBatchInfoId")
                        .HasDatabaseName("ix_lesson_lesson_batch_info_id");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AcademicDisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_discipline_id");

                    b.Property<bool>("AllowCombining")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_combining");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("Date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("Date")
                        .HasColumnName("date_to");

                    b.Property<string>("FlexibilityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flexibility_type");

                    b.Property<int?>("HoursCost")
                        .HasColumnType("integer")
                        .HasColumnName("hours_cost");

                    b.Property<int>("LessonsPerWeekCount")
                        .HasColumnType("integer")
                        .HasColumnName("lessons_per_week_count");

                    b.Property<string>("RepeatType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repeat_type");

                    b.Property<int?>("TotalHoursCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_hours_count");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_lesson_batch_info");

                    b.HasIndex("AcademicDisciplineId")
                        .HasDatabaseName("ix_lesson_batch_info_academic_discipline_id");

                    b.ToTable("lesson_batch_info", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbPolicyViolation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("DayOfWeekTimeInterval")
                        .HasColumnType("text")
                        .HasColumnName("day_of_week_time_interval");

                    b.Property<string>("ErrorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_type");

                    b.Property<Guid?>("LessonBatchInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Timestamp")
                        .HasColumnType("text")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_policy_violation");

                    b.HasIndex("LessonBatchInfoId")
                        .HasDatabaseName("ix_policy_violation_lesson_batch_info_id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_policy_violation_lesson_id");

                    b.ToTable("policy_violation", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbPolicyViolationTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer")
                        .HasColumnName("target_type");

                    b.Property<Guid>("ViolationId")
                        .HasColumnType("uuid")
                        .HasColumnName("violation_id");

                    b.HasKey("Id")
                        .HasName("pk_policy_violation_target");

                    b.HasIndex("ViolationId")
                        .HasDatabaseName("ix_policy_violation_target_violation_id");

                    b.ToTable("policy_violation_target", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<bool?>("HasProjector")
                        .HasColumnType("boolean")
                        .HasColumnName("has_projector");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("RoomBoardType")
                        .HasColumnType("text")
                        .HasColumnName("room_board_type");

                    b.Property<string>("RoomType")
                        .HasColumnType("text")
                        .HasColumnName("room_type");

                    b.HasKey("Id")
                        .HasName("pk_room");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_room_campus_id");

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("Date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("Date")
                        .HasColumnName("date_to");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_schedule");

                    b.ToTable("schedule", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.HasIndex("StudentGroupId")
                        .HasDatabaseName("ix_student_student_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_student_user_id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbStudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("SemesterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("semester_number");

                    b.Property<string>("StudentGroupType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_group_type");

                    b.Property<int?>("StudentsCount")
                        .HasColumnType("integer")
                        .HasColumnName("students_count");

                    b.HasKey("Id")
                        .HasName("pk_student_group");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_student_group_schedule_id");

                    b.ToTable("student_group", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contacts")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("contacts");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("fullname");

                    b.HasKey("Id")
                        .HasName("pk_teacher");

                    b.ToTable("teacher", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbTeacherPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comment");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<string>("TeacherPreferenceType")
                        .HasColumnType("text")
                        .HasColumnName("teacher_preference_type");

                    b.Property<TimeOnly?>("TimeFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_from");

                    b.Property<TimeOnly?>("TimeTo")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_to");

                    b.HasKey("Id")
                        .HasName("pk_teacher_preference");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_teacher_preference_room_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_teacher_preference_schedule_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_teacher_preference_teacher_id");

                    b.ToTable("teacher_preference", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TimestampTz")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("lesson_batch_info_room", b =>
                {
                    b.Property<Guid>("lesson_batch_info_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<Guid>("room_id")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("lesson_batch_info_id", "room_id")
                        .HasName("pk_lesson_batch_info_room");

                    b.HasIndex("lesson_batch_info_id")
                        .HasDatabaseName("ix_lesson_batch_info_room_batch_id");

                    b.HasIndex("room_id")
                        .HasDatabaseName("ix_lesson_batch_info_room_room_id");

                    b.ToTable("lesson_batch_info_room", (string)null);
                });

            modelBuilder.Entity("lesson_batch_info_student_group", b =>
                {
                    b.Property<Guid>("lesson_batch_info_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<Guid>("student_group_id")
                        .HasColumnType("uuid")
                        .HasColumnName("student_group_id");

                    b.HasKey("lesson_batch_info_id", "student_group_id")
                        .HasName("pk_lesson_batch_info_student_group");

                    b.HasIndex("lesson_batch_info_id")
                        .HasDatabaseName("ix_lesson_batch_info_student_group_batch_id");

                    b.HasIndex("student_group_id")
                        .HasDatabaseName("ix_lesson_batch_info_student_group_student_group_id");

                    b.ToTable("lesson_batch_info_student_group", (string)null);
                });

            modelBuilder.Entity("lesson_batch_info_teacher", b =>
                {
                    b.Property<Guid>("lesson_batch_info_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_batch_info_id");

                    b.Property<Guid>("teacher_id")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("lesson_batch_info_id", "teacher_id")
                        .HasName("pk_lesson_batch_info_teacher");

                    b.HasIndex("lesson_batch_info_id")
                        .HasDatabaseName("ix_lesson_batch_info_teacher_batch_id");

                    b.HasIndex("teacher_id")
                        .HasDatabaseName("ix_lesson_batch_info_teacher_teacher_id");

                    b.ToTable("lesson_batch_info_teacher", (string)null);
                });

            modelBuilder.Entity("lesson_room", b =>
                {
                    b.Property<Guid>("lesson_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("room_id")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("lesson_id", "room_id")
                        .HasName("pk_lesson_room");

                    b.HasIndex("lesson_id")
                        .HasDatabaseName("ix_lesson_room_lesson_id");

                    b.HasIndex("room_id")
                        .HasDatabaseName("ix_lesson_room_room_id");

                    b.ToTable("lesson_room", (string)null);
                });

            modelBuilder.Entity("lesson_student_group", b =>
                {
                    b.Property<Guid>("lesson_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("student_group_id")
                        .HasColumnType("uuid")
                        .HasColumnName("student_group_id");

                    b.HasKey("lesson_id", "student_group_id")
                        .HasName("pk_lesson_student_group");

                    b.HasIndex("lesson_id")
                        .HasDatabaseName("ix_lesson_student_group_lesson_id");

                    b.HasIndex("student_group_id")
                        .HasDatabaseName("ix_lesson_student_group_student_group_id");

                    b.ToTable("lesson_student_group", (string)null);
                });

            modelBuilder.Entity("lesson_teacher", b =>
                {
                    b.Property<Guid>("lesson_id")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<Guid>("teacher_id")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("lesson_id", "teacher_id")
                        .HasName("pk_lesson_teacher");

                    b.HasIndex("lesson_id")
                        .HasDatabaseName("ix_lesson_teacher_lesson_id");

                    b.HasIndex("teacher_id")
                        .HasDatabaseName("ix_lesson_teacher_teacher_id");

                    b.ToTable("lesson_teacher", (string)null);
                });

            modelBuilder.Entity("student_group_link", b =>
                {
                    b.Property<Guid>("parent_id")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("child_id")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.HasKey("parent_id", "child_id")
                        .HasName("pk_student_group_link");

                    b.HasIndex("child_id")
                        .HasDatabaseName("ix_student_group_link_child_id");

                    b.ToTable("student_group_link", (string)null);
                });

            modelBuilder.Entity("Dal.Entities.DbAcademicDiscipline", b =>
                {
                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_academic_discipline_db_schedule_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Dal.Entities.DbDayOfWeekTimeIntervalAssignment", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", null)
                        .WithMany("DayOfWeekTimeIntervals")
                        .HasForeignKey("LessonBatchInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_day_of_week_time_interval_assignment_db_lesson_batch_info_l");
                });

            modelBuilder.Entity("Dal.Entities.DbLesson", b =>
                {
                    b.HasOne("Dal.Entities.DbDayOfWeekTimeIntervalAssignment", "DayOfWeekTimeIntervalAssignment")
                        .WithMany()
                        .HasForeignKey("DayOfWeekTimeIntervalAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lesson_day_of_week_time_interval_assignment_day_of_week_tim");

                    b.HasOne("Dal.Entities.DbLessonBatchInfo", "LessonBatchInfo")
                        .WithMany()
                        .HasForeignKey("LessonBatchInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_db_lesson_batch_info_lesson_batch_info_id");

                    b.Navigation("DayOfWeekTimeIntervalAssignment");

                    b.Navigation("LessonBatchInfo");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfo", b =>
                {
                    b.HasOne("Dal.Entities.DbAcademicDiscipline", "AcademicDiscipline")
                        .WithMany("LessonBatchInfos")
                        .HasForeignKey("AcademicDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_academic_discipline_academic_discipline_id");

                    b.Navigation("AcademicDiscipline");
                });

            modelBuilder.Entity("Dal.Entities.DbPolicyViolation", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", "LessonBatchInfo")
                        .WithMany("Violations")
                        .HasForeignKey("LessonBatchInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_policy_violation_lesson_batch_info_lesson_batch_info_id");

                    b.HasOne("Dal.Entities.DbLesson", "Lesson")
                        .WithMany("Violations")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_policy_violation_lesson_lesson_id");

                    b.Navigation("Lesson");

                    b.Navigation("LessonBatchInfo");
                });

            modelBuilder.Entity("Dal.Entities.DbPolicyViolationTarget", b =>
                {
                    b.HasOne("Dal.Entities.DbPolicyViolation", "Violation")
                        .WithMany("Targets")
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_policy_violation_target_policy_violation_violation_id");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("Dal.Entities.DbRoom", b =>
                {
                    b.HasOne("Dal.Entities.DbCampus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_room_campus_campus_id");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("Dal.Entities.DbStudent", b =>
                {
                    b.HasOne("Dal.Entities.DbStudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_db_student_group_student_group_id");

                    b.HasOne("Dal.Entities.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_db_user_user_id");

                    b.Navigation("StudentGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dal.Entities.DbStudentGroup", b =>
                {
                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_group_schedule_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Dal.Entities.DbTeacherPreference", b =>
                {
                    b.HasOne("Dal.Entities.DbRoom", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_teacher_preference_room_room_id");

                    b.HasOne("Dal.Entities.DbSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_preference_schedule_schedule_id");

                    b.HasOne("Dal.Entities.DbTeacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_preference_teacher_teacher_id");

                    b.Navigation("Room");

                    b.Navigation("Schedule");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("lesson_batch_info_room", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", null)
                        .WithMany()
                        .HasForeignKey("lesson_batch_info_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_room_batch");

                    b.HasOne("Dal.Entities.DbRoom", null)
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_room_room");
                });

            modelBuilder.Entity("lesson_batch_info_student_group", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", null)
                        .WithMany()
                        .HasForeignKey("lesson_batch_info_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_student_group_batch");

                    b.HasOne("Dal.Entities.DbStudentGroup", null)
                        .WithMany()
                        .HasForeignKey("student_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_student_group_student_group");
                });

            modelBuilder.Entity("lesson_batch_info_teacher", b =>
                {
                    b.HasOne("Dal.Entities.DbLessonBatchInfo", null)
                        .WithMany()
                        .HasForeignKey("lesson_batch_info_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_teacher_batch");

                    b.HasOne("Dal.Entities.DbTeacher", null)
                        .WithMany()
                        .HasForeignKey("teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_batch_info_teacher_teacher");
                });

            modelBuilder.Entity("lesson_room", b =>
                {
                    b.HasOne("Dal.Entities.DbLesson", null)
                        .WithMany()
                        .HasForeignKey("lesson_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_room_lesson");

                    b.HasOne("Dal.Entities.DbRoom", null)
                        .WithMany()
                        .HasForeignKey("room_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_room_room");
                });

            modelBuilder.Entity("lesson_student_group", b =>
                {
                    b.HasOne("Dal.Entities.DbLesson", null)
                        .WithMany()
                        .HasForeignKey("lesson_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_student_group_lesson");

                    b.HasOne("Dal.Entities.DbStudentGroup", null)
                        .WithMany()
                        .HasForeignKey("student_group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_student_group_student_group");
                });

            modelBuilder.Entity("lesson_teacher", b =>
                {
                    b.HasOne("Dal.Entities.DbLesson", null)
                        .WithMany()
                        .HasForeignKey("lesson_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_teacher_lesson");

                    b.HasOne("Dal.Entities.DbTeacher", null)
                        .WithMany()
                        .HasForeignKey("teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lesson_teacher_teacher");
                });

            modelBuilder.Entity("student_group_link", b =>
                {
                    b.HasOne("Dal.Entities.DbStudentGroup", null)
                        .WithMany()
                        .HasForeignKey("child_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_group_link_child");

                    b.HasOne("Dal.Entities.DbStudentGroup", null)
                        .WithMany()
                        .HasForeignKey("parent_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_group_link_parent");
                });

            modelBuilder.Entity("Dal.Entities.DbAcademicDiscipline", b =>
                {
                    b.Navigation("LessonBatchInfos");
                });

            modelBuilder.Entity("Dal.Entities.DbLesson", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("Dal.Entities.DbLessonBatchInfo", b =>
                {
                    b.Navigation("DayOfWeekTimeIntervals");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("Dal.Entities.DbPolicyViolation", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
